### ISSUE TITLE
[bug]: Ambiguous error codes

### ISSUE THREAD

**Issue by marcfir** [robert-burger/libethercat#18]
The error codes in
https://github.com/robert-burger/libethercat/blob/cee650055c7fd082c82951883aa52134440ed281/include/libethercat/error_codes.h#L86-L88
point to the same numbers here.
https://github.com/robert-burger/libethercat/blob/cee650055c7fd082c82951883aa52134440ed281/include/libethercat/error_codes.h#L104-L106

Suggestion to change the numbers to:
```
#define EC_ERROR_MAILBOX_OUT_OF_SEND_BUFFERS    (EC_ERROR_MAILBOX_MASK | 0x00010000)        //!< \brief Mailbox ran out of read buffers. See LEC_MAX_MBX_ENTRIES.
#define EC_ERROR_MAILBOX_OUT_OF_WRITE_BUFFERS   (EC_ERROR_MAILBOX_MASK | 0x00020000)        //!< \brief Mailbox ran out of write buffers. See LEC_MAX_MBX_ENTRIES.
#define EC_ERROR_MAILBOX_BUFFER_TOO_SMALL       (EC_ERROR_MAILBOX_MASK | 0x00040000)        //!< \brief Mailbox buffer is too small.
```

**Comment by robert-burger** [comment]
thanks, fixed in 91d4b21ca67c027fbbd601bf4a2c3cb2aa80e25c
