### ISSUE TITLE
[bug]: ec_soe_write() never returns EC_OK

### ISSUE THREAD

**Issue by marcfir** [robert-burger/libethercat#19]
Hi Robert,
It seems that ec_soe_write() never returns EC_OK even though it writes successfully, or have I missed something?
https://github.com/robert-burger/libethercat/blob/cee650055c7fd082c82951883aa52134440ed281/src/soe.c#L331

**Comment by robert-burger** [comment]
yes, you're right. it always returns one of the following errors:

```
EC_ERROR_MAILBOX_TIMEOUT
EC_ERROR_MAILBOX_NOT_SUPPORTED_SOE
EC_ERROR_MAILBOX_OUT_OF_WRITE_BUFFERS
```

so anywhere `ret` should be set to `EC_OK`.

**Comment by robert-burger** [comment]
added that in e0be7c856f12db2e3d3c1fcfaa47eb01c0a495c8
