### ISSUE TITLE
SOE mapping wrong byte length calculation for sm

### ISSUE THREAD

**Issue by marcfir** [robert-burger/libethercat#24]
Hi Robert,
I think that line 568 should be
`slv->sm[mdt_sm].len = (mdt_bits + 7u) / 8u; `
https://github.com/robert-burger/libethercat/blob/e0be7c856f12db2e3d3c1fcfaa47eb01c0a495c8/src/soe.c#L562-L570

**Comment by robert-burger** [comment]
thanks
