### ISSUE TITLE
ec_mbx_check: inconsistency between documentation and implementation

### ISSUE THREAD

**Issue by marcfir** [robert-burger/libethercat#27]
Hi Robert,
`ec_mbx_check()` returns a bool according to the documentation but the implementation returns
0 if mbx is supported, and an error (!0) if mbx is not supported.
https://github.com/robert-burger/libethercat/blob/fba7b24fb9829021ad9c9cd11830f7b1bfa84d98/src/mbx.c#L220-L241

Either the documentation or implementation should be fixed.

**Comment by robert-burger** [comment]
should be fixed with 0269ed882b71ef17d564bd9f55975e70379fee96
